### ISSUE TITLE
AcceleratorParserStage is not compatible with Stream Accelerator objects

### ISSUE THREAD

**Issue by Andful** [KULeuven-MICAS/stream#10]
Currently, stream uses the zigzag `AcceleratorParserStage` stage, which either accepts a string or a ZigZag's `Accelerator` object.
If the field `accelerator` is a ZigZag's `Accelerator`, then the stage finishes without errors but later stages error out. If a Stream's `Accelerator` object is passed, the stage does not recognize such object as an `Accelerator`.

**Comment by asyms** [comment]
Hi @Andful,

Is this still a problem or can I close this issue?

**Comment by Andful** [comment]
I personally steered away from using an accelerator object and have been using accelerators defined in a separate path. So, to answer your question, personally it has not been an issue for me.

**Comment by asyms** [comment]
This has been fixed in a recent ZigZag update
