### ISSUE TITLE
Some tiny errors in SimdParser and PoolingParser.

### ISSUE THREAD

**Issue by fhys** [KULeuven-MICAS/stream#20]
In stream/classes/io/onnx/simd.py and stream/classes/io/onnx/pooling.py, the OX and OY dimensions are incorrectly assigned, causing an exchange in dimension sizes between OX and OY. For example, if IX=640 and IY=512, this error makes OX=512 and OY=640.
```
            OX = oa_shape[2]
            OY = oa_shape[3]
```
In stream/classes/io/onnx/simd.py line 39-40.
```
            OX = oa_shape[2]
            OY = oa_shape[3]
```
In stream/classes/io/onnx/pooling.py line 63-64.
OX and OY is assigned correctly in stream/classes/io/onnx/conv.py line 89-90.
```
            OX = oa_shape[3]
            OY = oa_shape[2]
```

**Comment by asyms** [comment]
This has been fixed.
