### ISSUE TITLE
Should this not be min?

### ISSUE THREAD

**Issue by Andful** [KULeuven-MICAS/stream#24]
https://github.com/KULeuven-MICAS/stream/blob/ae7ed828baeb1d557f3874032737e3f613de9107/stream/classes/hardware/architecture/accelerator.py#L321

**Comment by asyms** [comment]
No. The `links` variable represents the links needed to transfer from Core A to core B. If one of these links has a lower bandwidth, we assume the worst-case transfer time across all of them.

Hope that clarifies your concern.

**Comment by Andful** [comment]
Bandwidth is inversely proportional to duration. You should either take the `max` of `link.bandwidth` or the `min` of `duration`. Here you are taking `max` of `duration`.

**Comment by Andful** [comment]
Oh nvm, I re-read your comment, now it makes sense. You are considering the worst-case transfer time.
