### ISSUE TITLE
Is this else supposed to be here?

### ISSUE THREAD

**Issue by Andful** [KULeuven-MICAS/stream#36]
Is this `else` supposed to be here?
From my understanding it sorts `evictable_tensors` if `evictable_tensors` is empty

https://github.com/KULeuven-MICAS/stream/blob/6ac88776d1b9e5698f39014500f3d0ae7cde20a7/stream/classes/cost_model/memory_manager.py#L263

**Comment by asyms** [comment]
The else statement should indeed not be there. It can be removed.

**Comment by asyms** [comment]
This will be fixed in https://github.com/KULeuven-MICAS/stream/pull/48
