### ISSUE TITLE
How to fix core allocation?

### ISSUE THREAD

**Issue by Andful** [KULeuven-MICAS/stream#44]
`core_allocation_is_fixed` does not seem to do anything

**Comment by asyms** [comment]
You are correct. I am in the process of adding the intended behavior for this.

**Comment by asyms** [comment]
Hi @Andful 

The behavior has been changed in the latest [PR](https://github.com/KULeuven-MICAS/stream/pull/47), by adding a stage called SetFixedAllocationPerformanceStage. You can find more details in the stage: https://github.com/KULeuven-MICAS/stream/blob/master/stream/stages/set_fixed_allocation_performance.py
